# Generated by Django 5.2.7 on 2025-10-22 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('status', models.CharField(default='not submitted', max_length=100)),
                ('best_mark', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts_left', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='labs.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('mark', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.IntegerField()),
                ('answers', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='labs.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
