# Generated by Django 5.2.7 on 2025-10-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_lab_options_submission_attempt'),
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
