# Generated by Django 5.2.7 on 2025-12-04 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_submission_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberPhysicalSystemSimulation',
            fields=[
                ('lab_type', models.CharField(choices=[('water_tank', 'Система контролю рівня води'), ('temperature', 'Система контролю температури'), ('speed_control', 'Система контролю швидкості'), ('pressure', 'Система контролю тиску')], default='water_tank', max_length=50)),
                ('state', models.CharField(choices=[('running', 'Запущена'), ('paused', 'Призупинена'), ('stopped', 'Зупинена')], default='stopped', max_length=20)),
                ('initial_value', models.FloatField(help_text='Початкове значення')),
                ('target_value', models.FloatField(help_text='Значення, до якого потрібно дійти')),
                ('current_value', models.FloatField(help_text='Поточне значення системи')),
                ('error_threshold', models.FloatField(default=0.5, help_text='Допустимої відхилення')),
                ('kp', models.FloatField(default=0.5, help_text='Коефіцієнт P')),
                ('ki', models.FloatField(default=0.1, help_text='Коефіцієнт I')),
                ('kd', models.FloatField(default=0.2, help_text='Коефіцієнт D')),
                ('simulation_time', models.FloatField(default=0, help_text='Поточний час симуляції (сек)')),
                ('total_duration', models.FloatField(default=120, help_text='Загальна тривалість (сек)')),
                ('simulation_data', models.JSONField(default=list, help_text="Масив точок даних: [{'time': ..., 'value': ..., 'error': ...}]")),
                ('success', models.BooleanField(default=False, help_text='Чи досягнута мета')),
                ('final_score', models.FloatField(default=0, help_text='Підсумковий бал (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cps_simulation', to='labs.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
